import { spaceGrotesk } from "@/utils/fonts";
import "../globals.css";


export const metadata = {
  title: "Remco Jonk | Front-End & Webflow Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  );
}
