import { spaceGrotesk } from "@/utils/fonts";
import "./globals.css";
import Navbar from "@/ui/components/navbar/navbar.component";
import GradientBackgroundComponent from "@/ui/components/gradient-background/gradient-background.component";
import Footer from "@/ui/sections/footer-section/footer.component";


export const metadata = {
  title: "Remco Jonk | Front-End & Webflow Developer | Alkmaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <Navbar/>
        <GradientBackgroundComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
